apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgresql
  namespace: ns-postgresql
spec:
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.0
    - timeo=60
    - retrans=10
  capacity:
    storage: 10Gi
  nfs:
    server: 10.0.0.31
    path: "/shares/share-282210b9-cf88-46e9-890e-9cd026d39a51"
  persistentVolumeReclaimPolicy: "Recycle"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgresql
  namespace: ns-postgresql
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: "pv-postgresql"
  storageClassName: ""
