apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pg
  namespace: lesson5
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: "pv-pg"
  storageClassName: ""
