---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedoom-deployment
  namespace: kubedoom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-kubedoom
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-kubedoom
    spec:
      containers:
      - image: storaxdev/kubedoom:0.5.0
        name: kubedoom-pod
        ports:
        - containerPort: 5900
          protocol: TCP
      hostNetwork: true
      serviceAccountName: kubedoom
